CREATE TABLE ports(
  id SERIAL PRIMARY KEY,
  name VARCHAR(150) UNIQUE NOT NULL
);
GRANT ALL PRIVILEGES ON TABLE ports TO hero;

CREATE TABLE levels(
  id SERIAL PRIMARY KEY,
  name VARCHAR(150) UNIQUE NOT NULL
);
GRANT ALL PRIVILEGES ON TABLE levels TO hero;

CREATE TABLE manufactorers(
  id SERIAL PRIMARY KEY,
  name VARCHAR(150) UNIQUE NOT NULL
);
GRANT ALL PRIVILEGES ON TABLE manufactorers TO hero;

CREATE TABLE switches(
  id SERIAL PRIMARY KEY,
  name VARCHAR(250) UNIQUE NOT NULL,
  level_id INTEGER NOT NULL REFERENCES levels(id),
  manufactorer_id INTEGER NOT NULL REFERENCES manufactorers(id),
  costs MONEY NOT NULL,
  input_volts INTEGER NOT NULL,
  info VARCHAR(1000) NOT NULL
);
GRANT ALL PRIVILEGES ON TABLE switches TO hero;

CREATE TABLE switches_ports(
  switch_id INTEGER NOT NULL REFERENCES switches(id),
  port_id INTEGER NOT NULL REFERENCES ports(id)
);
GRANT ALL PRIVILEGES ON TABLE switches_ports TO hero;
